shell fish

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

cursor_shape          block
cursor_blink_interval -1
cursor_stop_blinking_after 15.0
cursor_trail              5
cursor_trail_decay        0.1 0.4

scrollback_lines 10000

copy_on_select        clipboard
mouse_hide_wait       3.0
url_style             curly
open_url_with         default
detect_urls           yes

enable_audio_bell no
visual_bell_duration 0.0

window_padding_width 4
hide_window_decorations no
confirm_os_window_close 1

tab_bar_edge   bottom
tab_bar_style  powerline
tab_powerline_style slanted

background_opacity 1.0

foreground              #b8c8d8
background              #191d2d
selection_foreground    #191d2d
selection_background    #3a5878

cursor                  #68a8a8
cursor_text_color       #191d2d

url_color               #6888a8

active_tab_foreground   #191d2d
active_tab_background   #5890a8
inactive_tab_foreground #b8c8d8
inactive_tab_background #2a3848
tab_bar_background      #141828

mark1_foreground #191d2d
mark1_background #6888a8
mark2_foreground #191d2d
mark2_background #5890a8
mark3_foreground #191d2d
mark3_background #60a0a0

color0  #191d2d
color8  #2a3848

color1  #b06858
color9  #c88070

color2  #68a898
color10 #80b8a8

color3  #6898a8
color11 #80b0c0

color4  #6888a8
color12 #80a0c0

color5  #8878a0
color13 #a090b8

color6  #60a0a0
color14 #78b8b0

color7  #b8c0c8
color15 #d0d8e0
